# submit_edep_read.sub
universe        = vanilla
executable      = run_edep_read.sh
arguments       = $(Process) 20
output          = logs/edep_read_$(Process).out
error           = logs/edep_read_$(Process).err
log             = logs/edep_read_$(Process).log
request_cpus    = 1
request_memory  = 2GB
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
initialdir      = /vols/dune/tta20/mach3/ND_LAr_Detector_Systematics_framework/edep-sim-truth-studies
+MaxRuntime = 14400
queue 256